CREATE TABLE RMS..BFL_TRANS_EXP(
    [STORE_ID] [varchar](30) NULL,
    [REG_ID] [varchar](20) NULL,
    [TRAN_SEQ] [varchar](30) NULL,
    [BUSINESS_DATE] [smalldatetime] NULL,
	[BFL_STORE_ID] [varchar](20) NULL,
	[BFL_REG_NO] [varchar](20) NULL,
	[BFL_INVOICE_NO] [varchar](20) NULL,
	[TRAN_TYPE] [varchar](10) NULL,
	[TRN_DATETIME] [smalldatetime] NULL,
	[EXPORTED] [varchar](5) NULL,
	[ERROR] [varchar](MAX) NULL,
	[CREATE_DATETIME] [smalldatetime] NULL
);

CREATE TABLE RMS..BFL_RTLOG_CONFIG(
	[RECORD_TYPE] [varchar](50) NULL,
	[BFL_VALUES] [varchar](50) NULL,
	[BFL_CODES] [varchar](50) NULL,
	[RESA_VALUES] [varchar](100) NULL,
	[RESA_CODES] [varchar](50) NULL
);

CREATE SEQUENCE TRANS_SEQ
 AS [bigint]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999
 CACHE;
 
CREATE SEQUENCE Shipment_Seq
 AS [bigint]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 99999999999999999999999999
 CACHE;
 
CREATE SEQUENCE TRANS_PAYROLL_SEQ
 AS [bigint]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999
 CACHE;

CREATE SEQUENCE Transfer_SEQ
 AS [bigint]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999
 CACHE;
 
CREATE SEQUENCE PriceAgeing_SEQ
 AS [bigint]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999
 CACHE;

CREATE TABLE RMS..BFL_EXP_DATA(
    [BFL_INVOICE_NO] [varchar](50) NULL,
	[BFL_TABLE_NAME] [varchar](30) NULL,
	[TRAN_TYPE] [varchar](40) NULL,
	[TRN_DATETIME] [smalldatetime] NULL,
	[EXPORTED] [varchar](5) NULL,
	[ERROR] [varchar](MAX) NULL,
	[CREATE_DATETIME] [smalldatetime] NULL
);

CREATE TABLE BFL_RIT_JOB_CONFIG(
	[jobId] [bigint] NOT NULL,
	[adhocRun] [bit] NOT NULL,
	[alertEmailSubject] [varchar](255) NULL,
	[createTime] [datetime2](7) NULL,
	[cronExpression] [varchar](255) NOT NULL,
	[email] [varchar](255) NOT NULL,
	[enabled] [bit] NOT NULL,
	[jobClassName] [varchar](255) NOT NULL,
	[jobName] [varchar](255) NOT NULL,
	[updateTime] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[jobId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[BFL_RIT_PROCESS_TS](
	[JOB_ID] [varchar](255) NOT NULL,
	[JOB_NAME] [varchar](255) NULL,
	[LAST_SUCCESS_PROCESS_TS] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[JOB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[BFL_RIT_ROLE](
	[id] [bigint] NOT NULL,
	[name] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE bfl_rit_users_roles (
	[user_id] [bigint] NOT NULL,
	[role_id] [bigint] NOT NULL
) ON [PRIMARY];


CREATE TABLE BFL_RIT_USER (
	[id] [bigint] NOT NULL,
	[email] [varchar](255) NULL,
	[firstName] [varchar](255) NULL,
	[lastName] [varchar](255) NULL,
	[password] [varchar](255) NULL,
	[temporaryPassword] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UKsjy9n6elfhp6a498o9jwvaj7f] UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

ALTER TABLE [dbo].[bfl_rit_users_roles]  WITH CHECK ADD  CONSTRAINT [FK64t4cbgcdvc1ja14byavji2ki] FOREIGN KEY([user_id])
REFERENCES [dbo].[BFL_RIT_USER] ([id]);

ALTER TABLE [dbo].[bfl_rit_users_roles] CHECK CONSTRAINT [FK64t4cbgcdvc1ja14byavji2ki];

ALTER TABLE [dbo].[bfl_rit_users_roles]  WITH CHECK ADD  CONSTRAINT [FKqgtybifwb84rhknvr9dq8shwk] FOREIGN KEY([role_id])
REFERENCES [dbo].[BFL_RIT_ROLE] ([id]);

ALTER TABLE [dbo].[bfl_rit_users_roles] CHECK CONSTRAINT [FKqgtybifwb84rhknvr9dq8shwk];

--This is for GIN in RMS DB.

CREATE SEQUENCE RMS..GIN_SEQ
AS [bigint]
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
CACHE;

CREATE TABLE RMS..BFL_WMS_EXP_DATA(
	[BFL_Transfer_NO] [varchar](50) NULL,
	[BFL_TABLE_NAME] [varchar](30) NULL,
	[TRAN_TYPE] [varchar](40) NULL,
	[TRN_DATETIME] [smalldatetime] NULL,
	[EXPORTED] [varchar](5) NULL,
	[ERROR] [varchar](max) NULL,
	[CREATE_DATETIME] [smalldatetime] NULL,
	[RMS_Transfer_NO] [varchar](50) NULL
);

CREATE TABLE RMS..BFL_WH_TO_WH_EXP_DATA(
	[BFL_Transfer_NO] [varchar](50) NULL,
	[BFL_TABLE_NAME] [varchar](30) NULL,
	[TRAN_TYPE] [varchar](40) NULL,
	[TRN_DATETIME] [smalldatetime] NULL,
	[EXPORTED] [varchar](5) NULL,
	[ERROR] [varchar](max) NULL,
	[CREATE_DATETIME] [smalldatetime] NULL,
	[RMS_Transfer_NO] [varchar](50) NULL
);

CREATE TABLE RMS..BFL_STORE_CONFIG (
	[COUNTRY] [varchar](30) NULL,
	[STORE_NAME] [varchar](50) NULL,
	[STORE_ID] [varchar](40) NULL,
	[STORE_SHORT_NAME] [varchar](30) NULL,
	[VAT_REGION] [varchar](30) NULL,
	[STATUS] [varchar](5) NULL
);

CREATE TABLE RMS..BFL_VAT_REGION (
	[VAT_REGION] [varchar](30) NULL,
	[VAT_CODE] [varchar](30) NULL,
	[VAT_CODE_RATE] [varchar](5) NULL,
	[VAT_TYPE] [varchar](30) NULL
);

insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLABUSHAGARA','1001',	'BFL-ABUSH','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('ACC','1002','BFL-ACC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('ABUMALL','1003','BFL-ADM','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLAINMALL','1004','BFL-AINM','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLAJMAN','1005','BFL-AJM','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BARSHA','1006','BFL-BAR','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BURJUMAN','1008','BFL-BRJM','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLCIRCLEMALL','1010','BFL-CIRC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLCITYWALK','1011','BFL-CITY','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLDALMA','1013','BFL-DALMA','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLDBMALL','1014','BFL-DBM','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLDCC','1015','BFL-DCC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLDFC','1016','BFL-DFC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLMARINA','1018','BFL-DMM','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('DOM','1019','BFL-DOM','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLFLAGSHIPDXB','1020','BFL-DXB','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLFUJAIRAH','1021','BFL-FUJ','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLFORSAN','1022','BFL-FUR','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLGHURAIR','1023','BFL-GHU','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('GHAZAL','1024','BFL-GHZL','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('ABUDHABI','1025','BFL-HMDN','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLIBN','1026','BFL-IBN','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLJBR','1027','BFL-JBR','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('ALKHAN','1028','BFL-KHAN','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('KHALIDIA','1029','BFL-KHLD','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('METROLINK','1030','BFL-MTRL','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLMOTORCITY','1032','BFL-MTRC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYBFLDFC','1034','BFL-DFC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLMUSHRIF','1035','BFL-MUSH','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYBFLOASIS','1035','BFL-SIL','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLNAKHEEL','1036','BFL-NAKH','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLRAK','1037','BFL-RAK','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYBFLRAK','1037','BFL-RAK','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLSAHARA','1038','BFL-SAHARA','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('SCC','1039','BFL-SCC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLSHJCENTRAL','1040','BFL-SHC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLSHINDAGA','1041','BFL-SHIN','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLOASIS','1043','BFL-SIL','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLSPRINGS','1044','BFL-SPRG','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLSUQEIM','1045','BFL-SUQ','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLTECHNOSTORE','1046','BFL-TEC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('UPTOWN','1047','BFL-UPT','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('WMALL','1048','BFL-WAH','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLWTC','1049','BFL-WTC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLYASMALL','1050','BFL-YASM','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('YASMEEN','1051','BFL-YSMN','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('HFLIBN','1053','HFL-IBN','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('HFLNAKHEEL','1054','HFL-NAKH','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('LFLDFC','1056','LFL-DFC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('WTC','1060','TCM-WTC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('TFL','1062','TFL-BAR','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('TFLIBN','1063','TFL-IBN','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('TFLMURAQQABAT','1065','TFL-MURQ','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('TFLUPTOWN','1066','TFL-UPT','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('TFLWTC','1067','TFL-WTC','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLRYDEXIT6','2001','BFL-BSA','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLRYDEXIT6-T','2001','BFL-BSA','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLRYDKHURAIS','2002','BFL-BSB','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLRYDKHURAIS-T','2002','BFL-BSB','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLKNGABD','2003','BFL-BSE','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLRYDGALLERY','2003','BFL-BSC','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLRYDGALLERY-T','2003','BFL-BSC','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLOTHAIMMALL','2007','BFL-BSG','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLIBDAAPLAZA','2008','BFL-BSH','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLLOCALIZER','2009','BFL-BSI','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLSAHARAMALL','2010','BFL-BSJ','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLALRAI','3001','BFL-ALR','4000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLKUWAITR1','3002','BFL-BKR','4000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLKUWAITR1-T','3002','BFL-BKR','4000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLHAWALI','3003','BFL-HAW','4000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('P2KUWAIT','3004','BFL-PKT','4000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('P2KUWAIT-T','3004','BFL-PKT','4000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('P2KUWAIT-W','3004','BFL-PKT','4000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLSHUWEIKH','3005','BFL-SHU','4000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLSHUWEIKH-T','3005','BFL-SHU','4000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLSALMIYA','3006','BFL-TER','4000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('KUWAIT-T','3006','BFL-TER','4000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('LFLMOTORCITY','3007','LFL-MCT','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLALKHOUD','4001','BFL-ALKH','3000','OMAN','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLALKHOUD-T','4001','BFL-ALKH','3000','OMAN','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLAVENUES','4002','BFL-AVEN','3000','OMAN','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLAVENUES-T','4002','BFL-AVEN','3000','OMAN','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLBAHJA','4003','BFL-BAHJ','3000','OMAN','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLBAHJA-T','4003','BFL-BAHJ','3000','OMAN','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLOMANMALL','4005','BFL-OMAN','3000','OMAN','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLOMANMALL-T','4005','BFL-OMAN','3000','OMAN','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLALSAAD','5001','BFL-ALS','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLALSAAD-T','5001','BFL-ALS','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLDOHACC','5002','BFL-BQB','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLDOHACC-T','5002','BFL-BQB','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLHYATTPLAZA','5005','BFL-PLZ','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLHYATTPLAZA-H','5005','BFL-PLZ','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLHYATTPLAZA-T','5005','BFL-PLZ','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLVENDOME','5006','BFL-VEN','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLVENDOME-H','5006','BFL-VEN','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLVENDOME-T','5006','BFL-VEN','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLD2AKOYA',' ','BFL-D2A','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLKSAR1',' ','BFL-BSD','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLKSAR1-T',' ','BFL-BSD','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLOMANR1',' ','BFL-BOR','4000','OMAN','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLQATARR1',' ','BFL-BQR','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLQATARR1-H',' ','BFL-BQR','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLQATARR1-T',' ','BFL-BQR','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLUPTOWN',' ','BFL-BUP','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('LFLBUFFER',' ','NULL','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('LFLKHIRAN',' ','LFL-KHI','3000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('METHA',' ','BFL-METH','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MURAQQABAT',' ','BFL-MURQ','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYBFLMUSHRIF',' ','BFL-MUSH','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYBFLSUQEIM',' ','BFL-SUQ','','','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYHFLIBN',' ','HFL-IBN','','','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYKHIRAN',' ','MUY-KHI','3000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYKSAR1',' ','BFL-BSD','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYP2KSA',' ','BFL-P2K','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYP2KUWAIT',' ','BFL-PKT','3000','KUWAIT','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYP2QATAR',' ','BFL-P2Q','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('MUYQATARR1',' ','BFL-BQR','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('ONLINE','1000','ONLINE','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('ONLINESUMMER',' ','ONLINE','','','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('ONLINEWINTER',' ','ONLINE','','','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('P2KSA',' ','BFL-P2K','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('P2KSA-T',' ','BFL-P2K','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('P2KSA-W',' ','BFL-P2K','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('P2QATAR',' ','BFL-P2Q','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('P2QATAR-H',' ','BFL-P2Q','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('P2QATAR-T',' ','BFL-P2Q','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('P2QATAR-W',' ','BFL-P2Q','5000','QATAR','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('PAOLA',' ','MUM-PAO','','MALTA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('STUDIOSUMMER',' ','ONLINE','','','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('STUDIOWINTER',' ','ONLINE','','','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('VALLETTA',' ','MUY-VLL','','MALTA','A');


INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('1000', 'S10', '10', 'Standard VAT 10%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('1000', 'S', '5', 'Standard VAT 5%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('1000', 'S15', '15', 'Standard VAT 15%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('1000', 'E', '0', 'Exempt');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('1000', 'C', '0', 'Composite');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('1000', 'Z', '0', 'Zero Vat');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('1000', 'TOTAX', '0', 'Total Tax');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('2000', 'S10', '10', 'Standard VAT 10%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('2000', 'S', '5', 'Standard VAT 5%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('2000', 'S15', '15', 'Standard VAT 15%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('2000', 'E', '0', 'Exempt');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('2000', 'C', '0', 'Composite');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('2000', 'Z', '0', 'Zero Vat');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('2000', 'TOTAX', '0', 'Total Tax');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('3000', 'S10', '10', 'Standard VAT 10%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('3000', 'S', '5', 'Standard VAT 5%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('3000', 'S15', '15', 'Standard VAT 15%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('3000', 'E', '0', 'Exempt');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('3000', 'C', '0', 'Composite');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('3000', 'Z', '0', 'Zero Vat');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('3000', 'TOTAX', '0', 'Total Tax');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('4000', 'S10', '10', 'Standard VAT 10%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('4000', 'S', '5', 'Standard VAT 5%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('4000', 'S15', '15', 'Standard VAT 15%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('4000', 'E', '0', 'Exempt');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('4000', 'C', '0', 'Composite');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('4000', 'Z', '0', 'Zero Vat');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('4000', 'TOTAX', '0', 'Total Tax');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('5000', 'S10', '10', 'Standard VAT 10%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('5000', 'S', '5', 'Standard VAT 5%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('5000', 'S15', '15', 'Standard VAT 15%');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('5000', 'E', '0', 'Exempt');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('5000', 'C', '0', 'Composite');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('5000', 'Z', '0', 'Zero Vat');
INSERT INTO RMS..BFL_VAT_REGION(VAT_REGION, VAT_CODE, VAT_CODE_RATE, VAT_TYPE) values('5000', 'TOTAX', '0', 'Total Tax');

CREATE TABLE RMS..STORE_HEADER_CONFIG(
TRANSFER_TYPE varchar(50),
WH_LOCATION varchar(50),
WH_ID varchar(20)
)

INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('DAMAGE', 'Factory', '10004');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('ONLINE', 'ONLINE', '1000');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('OTHERS', 'TECHNO', '10001');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('REPAIR', 'Factory', '10004');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('QUALITY ISSUES', 'Factory', '10004');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('ONLINE RETURNS', 'ONLINE', '1000');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('REPETITIVES', 'TECHNO', '10001');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('NO Barcode', 'TECHNO', '10001');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('DAMAGED IN SHOP', 'Factory', '10004');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('RECALLS', 'TECHNO', '10001');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('CUSTOMER DAMAGE', 'Factory', '10004');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('NON SALEABLE IT', 'Factory', '10004');
INSERT INTO RMS..STORE_HEADER_CONFIG(TRANSFER_TYPE, WH_LOCATION, WH_ID) values ('MKD', 'MKD', '10004');

CREATE TABLE RMS..BFL_WH_TO_ST_CONFIG(
TrfType varchar(5),
WH_LOCATION varchar(50),
WH_ID varchar(20)
)

INSERT INTO RMS..BFL_WH_TO_ST_CONFIG(TrfType, WH_LOCATION, WH_ID) values ('FT', 'TECHNO', '10001');
INSERT INTO RMS..BFL_WH_TO_ST_CONFIG(TrfType, WH_LOCATION, WH_ID) values ('FN', 'TECHNO', '10001');
INSERT INTO RMS..BFL_WH_TO_ST_CONFIG(TrfType, WH_LOCATION, WH_ID) values ('FO', 'JAFZA', '10002');

CREATE TABLE RMS..BFL_WMS_GIN_DATA(
	[BFL_Transfer_NO] [varchar](50) NULL,
	[BFL_TABLE_NAME] [varchar](30) NULL,
	[TRAN_TYPE] [varchar](40) NULL,
	[TRN_DATETIME] [smalldatetime] NULL,
	[EXPORTED] [varchar](5) NULL,
	[ERROR] [varchar](max) NULL,
	[CREATE_DATETIME] [smalldatetime] NULL,
	[RMS_Transfer_NO] [varchar](50) NULL
);

ALTER TABLE RMS..BFL_TRANS_EXP ALTER COLUMN TRAN_SEQ numeric(30);

update RMS..BFL_STORE_CONFIG set STORE_ID = '1030' WHERE store_name like 'METHA%';

update RMS..BFL_STORE_CONFIG set STORE_ID = '1012' WHERE STORE_NAME = 'BFLD2AKOYA';

insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('LFL - BFL SHOPPING CENTER','1057',	'LFL-MCT','1000','UAE','A');

alter table RMS..BFL_EXP_DATA alter column BFL_INVOICE_NO varchar(250);

insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLKNGABD','2005', 'BFL-BSE','2000','KSA','A');

update RMS..BFL_STORE_CONFIG set  store_id = '1033' where STORE_NAME = 'METROLINK';

CREATE SEQUENCE Shipment_Seq
 AS bigint
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 8888888888888888888
 CACHE;
 
CREATE TABLE RMS..BFL_CONTAINER_DETAILS(
	[oldContNo] [varchar](30) NULL,
	[newContNo] [varchar](30) NULL
);

CREATE TABLE RMS..BFL_CONT_DETAILS(
	[BFL_CONT_NO] [varchar](50) NULL,
	[BFL_TABLE_NAME] [varchar](30) NULL,
	[TRN_DATETIME] [smalldatetime] NULL,
	[EXPORTED] [varchar](5) NULL,
	[ERROR] [varchar](max) NULL,
	[CREATE_DATETIME] [smalldatetime] NULL
);

CREATE TABLE RMS..BFL_WH_TO_WH_EXP_DATA(
	[BFL_Transfer_NO] [varchar](50) NULL,
	[BFL_TABLE_NAME] [varchar](30) NULL,
	[TRAN_TYPE] [varchar](40) NULL,
	[TRN_DATETIME] [smalldatetime] NULL,
	[EXPORTED] [varchar](5) NULL,
	[ERROR] [varchar](max) NULL,
	[CREATE_DATETIME] [smalldatetime] NULL,
	[RMS_Transfer_NO] [varchar](50) NULL
);

---- 22nd July...

DELETE FROM RMS..BFL_STORE_CONFIG WHERE store_name in ('P2KUWAIT', 'P2KUWAIT-T', 'P2KUWAIT-W', 'MUYP2KSA', 
'MUYP2KUWAIT', 'MUYP2QATAR', 'P2KSA', 'P2KSA-T', 'P2KSA-W', 'P2QATAR', 'P2QATAR-H', 'P2QATAR-T', 'P2QATAR-W', 
'MUYKSAR1', 'MUYQATARR1', 'BFLKSAR1', 'BFLKSAR1-T', 'BFLOMANR1', 'BFLQATARR1', 'BFLQATARR1-H', 'BFLQATARR1-T');

Drop table RMS..BFL_WH_CONFIG;

CREATE TABLE RMS..BFL_WH_CONFIG(
	[RMS_VIRUAL_WAREHOUSE_ID] [varchar](50) NULL,
	[RMS_PHYSICAL_WAREHOUSE_ID] [varchar](30) NULL,
	[RMS_WAREOUSE_TYPE] [varchar](40) NULL,
	[BFL_WAREHOUSE_NAME] [varchar](30) NULL
);

insert into RMS..BFL_WH_CONFIG(RMS_VIRUAL_WAREHOUSE_ID, RMS_PHYSICAL_WAREHOUSE_ID, RMS_WAREOUSE_TYPE, BFL_WAREHOUSE_NAME) values (11001, 10001,	'Virtual',	'TECHNO');
insert into RMS..BFL_WH_CONFIG(RMS_VIRUAL_WAREHOUSE_ID, RMS_PHYSICAL_WAREHOUSE_ID, RMS_WAREOUSE_TYPE, BFL_WAREHOUSE_NAME) values (12001, 10002,	'Virtual',	'JAFZA');
insert into RMS..BFL_WH_CONFIG(RMS_VIRUAL_WAREHOUSE_ID, RMS_PHYSICAL_WAREHOUSE_ID, RMS_WAREOUSE_TYPE, BFL_WAREHOUSE_NAME) values (13001, 10003, 'Virtual', 'YOTO');
insert into RMS..BFL_WH_CONFIG(RMS_VIRUAL_WAREHOUSE_ID, RMS_PHYSICAL_WAREHOUSE_ID, RMS_WAREOUSE_TYPE, BFL_WAREHOUSE_NAME) values (14001, 10004, 'Virtual', 'RecoveryFactory');
insert into RMS..BFL_WH_CONFIG(RMS_VIRUAL_WAREHOUSE_ID, RMS_PHYSICAL_WAREHOUSE_ID, RMS_WAREOUSE_TYPE, BFL_WAREHOUSE_NAME) values (1000, 1000, 'Virtual', 'ONLINE');

insert into RMS..BFL_WH_CONFIG(RMS_VIRUAL_WAREHOUSE_ID, RMS_PHYSICAL_WAREHOUSE_ID, RMS_WAREOUSE_TYPE, BFL_WAREHOUSE_NAME) values (11003, 10001, 'Virtual', 'P2KSA-TECHNO');
insert into RMS..BFL_WH_CONFIG(RMS_VIRUAL_WAREHOUSE_ID, RMS_PHYSICAL_WAREHOUSE_ID, RMS_WAREOUSE_TYPE, BFL_WAREHOUSE_NAME) values (11004, 10001, 'Virtual', 'P2KUWAIT-TECHNO');
insert into RMS..BFL_WH_CONFIG(RMS_VIRUAL_WAREHOUSE_ID, RMS_PHYSICAL_WAREHOUSE_ID, RMS_WAREOUSE_TYPE, BFL_WAREHOUSE_NAME) values (11005, 10001, 'Virtual', 'P2QATAR-TECHNO');
insert into RMS..BFL_WH_CONFIG(RMS_VIRUAL_WAREHOUSE_ID, RMS_PHYSICAL_WAREHOUSE_ID, RMS_WAREOUSE_TYPE, BFL_WAREHOUSE_NAME) values (12002, 10001, 'Virtual', 'P2KSA-Jafza');
insert into RMS..BFL_WH_CONFIG(RMS_VIRUAL_WAREHOUSE_ID, RMS_PHYSICAL_WAREHOUSE_ID, RMS_WAREOUSE_TYPE, BFL_WAREHOUSE_NAME) values (12003, 10001, 'Virtual', 'P2KUWAIT-Jafza');
insert into RMS..BFL_WH_CONFIG(RMS_VIRUAL_WAREHOUSE_ID, RMS_PHYSICAL_WAREHOUSE_ID, RMS_WAREOUSE_TYPE, BFL_WAREHOUSE_NAME) values (12005, 10001, 'Virtual', 'P2QATAR-Jafza');

CREATE TABLE RMS..BFL_WMS_GRN_DATA(
	[BFL_Transfer_NO] [varchar](50) NULL,
	[BFL_TABLE_NAME] [varchar](30) NULL,
	[TRAN_TYPE] [varchar](40) NULL,
	[TRN_DATETIME] [smalldatetime] NULL,
	[EXPORTED] [varchar](5) NULL,
	[ERROR] [varchar](max) NULL,
	[CREATE_DATETIME] [smalldatetime] NULL,
	[RMS_Transfer_NO] [varchar](50) NULL
);

update RMS..BFL_STORE_CONFIG set STORE_ID = '1012', VAT_REGION = '1000', COUNTRY = 'UAE' WHERE STORE_NAME = 'BFLD2AKOYA';
update RMS..BFL_STORE_CONFIG set STORE_ID = '1047', VAT_REGION = '1000', COUNTRY = 'UAE' WHERE STORE_NAME = 'BFLUPTOWN';
update RMS..BFL_STORE_CONFIG set STORE_ID = '3007', VAT_REGION = '1000', COUNTRY = 'UAE' WHERE STORE_NAME = 'LFLKHIRAN';
update RMS..BFL_STORE_CONFIG set STORE_ID = '1030', VAT_REGION = '1000', COUNTRY = 'UAE' WHERE STORE_NAME = 'METHA';
update RMS..BFL_STORE_CONFIG set STORE_ID = '1034', VAT_REGION = '1000', COUNTRY = 'UAE' WHERE STORE_NAME = 'MURAQQABAT';
update RMS..BFL_STORE_CONFIG set STORE_ID = '1035', VAT_REGION = '1000', COUNTRY = 'UAE' WHERE STORE_NAME = 'MUYBFLMUSHRIF';
update RMS..BFL_STORE_CONFIG set STORE_ID = '1045', VAT_REGION = '1000', COUNTRY = 'UAE' WHERE STORE_NAME = 'MUYBFLSUQEIM';
update RMS..BFL_STORE_CONFIG set STORE_ID = '1053', VAT_REGION = '1000', COUNTRY = 'UAE' WHERE STORE_NAME = 'MUYHFLIBN';
update RMS..BFL_STORE_CONFIG set STORE_ID = '3008', VAT_REGION = '1000', COUNTRY = 'UAE' WHERE STORE_NAME = 'MUYKHIRAN';
update RMS..BFL_STORE_CONFIG set STORE_ID = '1000', VAT_REGION = '1000', COUNTRY = 'UAE' WHERE STORE_NAME = 'ONLINE';

insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLJEDDAHPARK','2015','BFL-JED','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLJEDAZIZ','2014','BFL-AZI','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLDMDAREEN','2012','BFL-ARE','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLJEDVILLAGE','2017','	BFL-JDV','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLJEDSALAM','2016','BFL-LAM','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLARABIANCNTR','1068','BFL-ARB','1000','UAE','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLDMAMWAJ','2011','BFL-WAJ','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLDMOTHAIM','2013','BFL-AIM','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLRYDPARK','2021','BFL-ARK','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLSAHARAMALL','2010','BFL-BSJ','2000','KSA','A');
insert into RMS..BFL_STORE_CONFIG(STORE_NAME, STORE_ID, STORE_SHORT_NAME, VAT_REGION, COUNTRY, STATUS) values ('BFLRYDGRANADA','2019','BFL-RYG','2000','KSA','A');
update RMS..BFL_STORE_CONFIG set STORE_ID = 1057 WHERE STORE_SHORT_NAME = 'LFL-MCT';

---- 17th August...

ALTER TABLE RMS..BFL_TRANS_EXP ADD STORE_CLOSE_DATE smalldatetime;

------------------------------------------------------------------------------------------------------------------------------------------------------

update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?' where jobClassName = 'ProcessDailyStoreClosingJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?', enabled = 1 where jobClassName = 'ProcessCloseShopDataJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/10 * * * ?' where jobClassName = 'ProcessReturnSalesDataJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?' where jobClassName = 'ProcessMissingBarcodeDetailJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/30 * * * ?' where jobClassName = 'ProcessOtherStoresReturnSalesJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/10 * * * ?' where jobClassName = 'ProcessSalesDataJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?' where jobClassName = 'ProcessStoreHeaderJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?' where jobClassName = 'ProcessInvoiceReprintHistoryJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?' where jobClassName = 'ProcessBflEWalletLogDataJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?' where jobClassName = 'ProcessGiftCardLogJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?' where jobClassName = 'ProcessPriceHeaderAgeingDataJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?' where jobClassName = 'ProcessPriceDetailAgeingDataJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?' where jobClassName = 'ProcessMissingBarcodeHeaderDataJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?' where jobClassName = 'ProcessWarehouseToStoreGrnDataJob';
update BFL_RIT_JOB_CONFIG set cronExpression = '0 0/59 * * * ?' where jobClassName = 'ProcessItemDeleteDataJob';
update BFL_RIT_JOB_CONFIG set email = 'amit.arora@trangile.com';
update BFL_RIT_JOB_CONFIG set enabled = 0 where jobClassName in ('ProcessWarehouseToStoreGrnDataJob', 'ProcessStoreHeaderJob');

DELETE FROM BFL_RIT_JOB_CONFIG where jobClassName in ('ProcessStoreToStoreGrnDataJob','ProcessStoreOpenJob', 'ProcessNotificationQueueJob', 'ProcessBFLOrderProcedureQueueJob');

update BFL_RIT_JOB_CONFIG set enabled = 0 where jobClassName in ('ProcessReturnSalesDataJob', 'ProcessOtherStoresReturnSalesJob', 'ProcessCloseShopDataJob');

CREATE TABLE RMS..MFCS_SUBCLASS(
	[Dept] [varchar](10) NULL,
	[Class] [varchar](10) NULL,
	[SubClass] [varchar](10) NULL,
	[SubClassId] [varchar](10) NULL,
	[GroupCode] [varchar](5) not NULL
	CONSTRAINT PK PRIMARY KEY (GroupCode)
);

create table RMS..BFL_ITEMS_EXP (
	CREATE_DATETIME smalldatetime Null,
	[ERROR] [varchar](MAX) NULL,
	Exported varchar(10) NULL, 
	ItemCode varchar(25) NULL
);


------------------------05 Oct ---------------------

ALter table RMS..MFCS_SUBCLASS add supplier varchar (20);
ALter table RMS..MFCS_SUBCLASS add SuppCode varchar (20);
ALter table RMS..MFCS_SUBCLASS add country varchar (20);

create table RMS..BFL_Avg_Cost_Items (
	CREATE_DATETIME smalldatetime Null,
	[ERROR] [varchar](MAX) NULL,
	Exported varchar(10) NULL, 
	ItemCode varchar(25) NULL
);

------------------------20 Nov ---------------------

Create table RMS..TEMP_ItemMaster(
ItemCode varchar(15),
Description	nvarchar(510),
ShortName	nvarchar(20),
UnitCode	nvarchar(6),
GroupCode	nvarchar(6),
CatCode	nvarchar(6),
MinLevel	numeric(9),
ReorderLevel	numeric(9),
StockInHand	numeric(9),
OnOrder	numeric(9),
CostRate	numeric(9),
OpeningStock	numeric(9),
OpCostRate	numeric(9),
Batch	varchar(1),
OpeningDate	smalldatetime,
CostPriceUpdated	varchar(1),
Remarks	nvarchar(500),
costcode	nvarchar(6),
ItemType	nvarchar(2),
ArabicItem	nvarchar(510),
Transfered	char(1),
ToPrint	char(1),
SubCatCode	varchar	(3),
ItemColor	varchar(20),
ItemSize	varchar	(20),
InActive	char	(1));

Create table RMS..Temp_ItemAttibutes(
ContNo	varchar	(20),
UPC	varchar	(30),
ItemName	varchar	(255),
GroupCode	varchar	(5),
Style	varchar	(500),
Color	varchar	(150),
Size	varchar	(100),
TrnDate	smalldatetime	(4),
TrnTime	time	(5),
UserName	varchar	(20),
Upload	varchar	(1),
StyleQty	numeric	(4),
Remarks	varchar	(500),
Brand	varchar	(255),
Gender	varchar	(25),
Season	varchar	(3),
GenBarcode	varchar	(15),
subcategory	varchar	(50));

create table RMS..tempPODATA (
OrderNo varchar (50), 
GroupCode varchar (5), 
StyleQty numeric (10)
);

Create table RMS..PurchaseOrderDetails(
JobNo	varchar	(20),
GroupCode	varchar	(3),
CatCode	varchar	(3),
Qty	numeric	(4),
Amount	numeric	(9),
DiscountPerc	numeric	(9),
PalletCnt	numeric	(4),
LoadQty	numeric	(4),
Discount	numeric	(9),
Shipment numeric(15));

Create table RMS..TEMP_UPCBarCodes (
BOLNO varchar(25),
TrnDate smalldatetime, 
UPC	varchar	(25),
DeptName varchar(50),
ItemName varchar(250),
OrgRetRate numeric(9),
Itemcode varchar(15),
UserID numeric(4),
ItemType varchar (1),
ShortSkirt varchar(25),
ShortUpdated varchar	(50),
Size1 varchar(100),
SizeUpdated	varchar(50),
WinterUpdated	varchar	no	50
SizeCheck	varchar	(1),
DHSCost	numeric	(9),
ClientCost	numeric	(9),
Vendor	varchar	(255),
GroupCode	varchar	(3),
Color	varchar	(100),
Style	varchar	(50),
shortname	varchar	(255),
TYPE1	varchar	(10),
GENDER	varchar	(25),
CountryOrigin	varchar	(20),
Material	varchar	(500),
subcategory	varchar	(50),
HSCode	varchar	(25),
RRPCurrency	varchar	(10),
COSTCURR	varchar	(6)));

-----------------------------------------------------------------------------------------------------------------------------------------------

create table RMS..missing_resa_items(
itemcode varchar(50)
);

-----------------------------------------------------------------------------------------------------------------------------------------------

create table RMS..BFL_INTEGRATION_DATA(
CONTAINER_MAPPING numeric, 
BUSINESS_DATE smalldatetime, 
ITEM_GROUPS numeric, 
ITEMS numeric, 
ITEM_RECLASSIFY numeric, 
ORDER_NEW numeric, 
ORDER_MOD numeric, 
ORDER_CANCELLED numeric, 
SHIPMENTS numeric, 
CONTAINER_ID numeric, 
MANIFEST_UPLOAD numeric, 
PRICE_CHANGES numeric, 
PROMOTIONS numeric, 
CLEARANCES numeric, 
BRANDS numeric, 
SUPPLIERS numeric, 
DIVISION numeric, 
DEPT numeric, 
CATEGORY numeric, 
SUBCATEGORY numeric
CONSTRAINT PK2 PRIMARY KEY (BUSINESS_DATE)
);

-----------------------------------------------------------------------------------------------------------------------------------------------

ALTER TABLE Temp_ItemAttibutes alter column styleQty numeric(20);


